### ISSUE TITLE
CRAN release

### ISSUE THREAD

**Issue by mhesselbarth** [connectscape/Makurhini#4]
Hello, 

First of all, thanks for working on this package and contributing it to the community. 

Are you planning to release the package on CRAN in the near future?

**Comment by OscarGOGO** [comment]
Hello!

Thank you very much for your message, I apologize for taking so long to reply, it's been a chaotic few days.  By the way, I congratulate you for your work, landscapemetrics is an impressive package.

Yes, It is one of our goals to get this package on CRAN. However, due to lack of time and experience, it is something that has not been able to be materialized; We will add one more function with a sliding window and we hope to submit Makurhini this year.

Regards,

Oscar

**Comment by mhesselbarth** [comment]
Hey, 

I am sure more people would use and access the package if it's on CRAN. It looks really interesting. 

Putting it on CRAN is actually quite straight forward. Just a few things to consider. Let me know if you need any help with that once you are at the stage of thinking about submitting it.
