### ISSUE TITLE
Error when calculating protected connected indicator

### ISSUE THREAD

**Issue by wxyang007** [connectscape/Makurhini#7]
Hi there,

I've been following the code on the [webpage](https://connectscape.github.io/Makurhini/articles/ProtConnIndicator.html) and have been having some troubles (the R version I'm using is 4.0.0 in Windows system; edit: I have the same errors for R 4.1.2 on my Mac).

1. I got an error when trying to calculate ProtConn for a single region.
` test.1 <- MK_ProtConn(nodes = Protected_areas, region = region, attribute = "Intersected area", area_unit = "ha", distance = list(type= "centroid"), distance_thresholds = c(10000, 30000), probability = 0.5, transboundary = 50000, LA = NULL, plot = TRUE, dPC = FALSE, write = NULL, SAGA = FALSE, intern = FALSE)`

Error in MK_ProtConn(nodes = Protected_areas, region = region, attribute = "Intersected area",  : 
  unused arguments (attribute = "Intersected area", dPC = FALSE, SAGA = FALSE)

It worked after I deleted the three arguments.

2. I also got different errors when trying to calculate ProtConn for multiple regions.
`test.2 <-  MK_ProtConnMult(nodes = Protected_areas, regions = regions,  area_unit = "ha", distance = list(type= "centroid"), distance_thresholds = c(10000, 30000), probability = 0.5, transboundary = 50000, plot = FALSE, write = NULL, parallel = FALSE, intern = FALSE)`
Error: ‘workers >= 1’ is not TRUE
In addition: Warning message:
Strategy 'multiprocess' is deprecated in future (>= 1.20.0). Instead, explicitly specify either 'multisession' or 'multicore'. In the current R session, 'multiprocess' equals 'multisession'.

I tried changing `parallel = TRUE`, and then got the following error message.

`test.2 <- MK_ProtConnMult(nodes = Protected_areas, regions = regions,  area_unit = "ha", distance = list(type= "centroid"), distance_thresholds = c(10000, 30000), probability = 0.5, transboundary = 50000, plot = FALSE, write = NULL, parallel = TRUE, intern = FALSE)`

Error in stopf("Unsupported type of 'workers' for evaluator of class %s: %s",  : 
Unsupported type of 'workers' for evaluator of class ‘FutureStrategy’, ‘tweaked’, ‘multiprocess’, ‘future’, ‘function’: logical 

It looks like a problem with multiprocessing in R, but I don't know how to fix it. Could you please give me some advice on the workaround of the errors? Thank you for your help in advance!

And thank you for this great package!

**Comment by wxyang007** [comment]
Also, I am wondering if the regions' projections are azimuthal equidistant centered on the centroid of the protected areas, and if protected areas smaller than 1 km2 after clipping with regions are removed in the analysis as detailed in the paper. Thanks!

**Comment by OscarGOGO** [comment]
Hi! Thanks for using Makurhini!

1. I got an error when trying to calculate ProtConn for a single region. 
R. You are absolutely right, the Makurhini page on Github needed to be updated (updated) and still had those arguments (attribute = "Intersected area", dPC = FALSE, SAGA = FALSE) currently removed. Preferably check the help section of the package, e.g. **MK_ProtConn?**

2. I also got different errors when trying to calculate ProtConn for multiple regions. 
R. The error is due to the parallel argument, in previous versions parallel was a logical value where FALSE indicated that the process should not be parallelized and TRUE indicated that it should be parallelized using the number of cores detected in your machine - 1. In recent versions, we decided to leave the allocation of cores to parallelize functions to the user, i.e. the parallel argument is now a **numerical value** ranging from 1 to n cores allocated directly by the user. When the parallel argument is not used, it must remain as NULL (default).

`test.2 <- MK_ProtConnMult(nodes = Protected_areas, regions = regions, area_unp´'it = "ha", distance = list(type= "centroid"), distance_thresholds = c(10000, 30000), probability = 0.5, transboundary = 50000, plot = FALSE, write = NULL, 
parallel = NULL intern = FALSE)`

3. Also, I am wondering if the regions' projections are azimuthal equidistant centered on the centroid of the protected areas, and if protected areas smaller than 1 km2 after clipping with regions are removed in the analysis as detailed in the paper. 
R. The answer to both questions is no, although we respect most of the elements of the methodology proposed in the articles by Saura and collaborators we decided to omit at least two of them, the first is the selection of patches after making the intersections between the region and the protected areas. This is because Makurhini arises from the needs of a couple of projects that evaluated connectivity in Mexico, Colombia and other countries in Latin America and the Caribbean, at the time we considered that the analysis should consider smaller patches because we considered that they could have a contribution to the model, for example as stepping stones. However, it seems to me that it should be a criterion that the user should be able to control, so we will soon add that argument in the functions that estimate the ProtConn indicator, thank you very much for the question. Regarding the projected coordinate system used by Saura (azimuthal equidistant projection), although it is an adequate system to reduce the distortion in for example the estimation of Euclidean distances, we consider that there are other projections that the user could consider as better for his analysis (it will depend on for example the scale of analysis) so for now we have decided to leave this in the hands of the users who can use the projected coordinate system that they consider adequate for their analysis and that should be assigned in their inputs.

Best,
Oscar
